### ISSUE TITLE
Translate "Policies: Repository Structure" into Korean

### ISSUE THREAD

**Issue by jung-youjin** [Azure/azure-sdk-korean#39]
## Document URL
Leave a URL to translate / to request a translation (ex. https://azure.github.io/azure-sdk-korean/general_introduction.html)

- https://azure.github.io/azure-sdk-korean/policies_repostructure.html

## Estimated Completion Schedule
_Please write down your expected completion schedule. (e.g. within 1 month, during December, etc.)
(This is not a schedule you must keep -if the schedule is too delayed, please leave it for another translator.)_

- 2021-11-07

## Related issues
_Refer to each version of the main issue to view the current request/progress of translation.
(If nothing special happens, you do not need to modify it.)_

- None

**Comment by ianychoi** [comment]
Closing this issue since the issue was address through another PR: https://github.com/Azure/azure-sdk-korean/pull/78
