### ISSUE TITLE
"Policies"를 "정책"으로 바꾸기

### ISSUE THREAD

**Issue by YJY1220** [Azure/azure-sdk-korean#48]
"Policies"를 "정책"으로 바꾸기

**Comment by ianychoi** [comment]
Confirming that this issue has been addressed through multiple PRs - anyone can check on the website:
- https://azure.github.io/azure-sdk-korean/policies_adoption.html
- https://azure.github.io/azure-sdk-korean/policies_repostructure.html
- https://azure.github.io/azure-sdk-korean/policies_repobranching.html
- https://azure.github.io/azure-sdk-korean/policies_pipelines.html
- https://azure.github.io/azure-sdk-korean/policies_reviewprocess.html
- https://azure.github.io/azure-sdk-korean/policies_releases.html
- https://azure.github.io/azure-sdk-korean/policies_releasenotes.html
- https://azure.github.io/azure-sdk-korean/policies_support.html
-
